---
driver:
  name: vagrant
  chef_version: latest
  linked_clone: true

verifier:
  name: inspec

client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

platforms:
- name: ubuntu-12.04
  run_list:
  - "recipe[apt]"

- name: ubuntu-14.04
  run_list:
  - "recipe[apt]"
- name: ubuntu-16.04
  run_list:
  - "recipe[apt]"

- name: debian-7.11
  run_list:
  - "recipe[apt]"

- name: centos-6.8
  run_list:
  - "recipe[yum]"
  - "recipe[yum-epel]"

- name: centos-7.4
  run_list:
  - "recipe[yum]"
  - "recipe[yum-epel]"

suites:
- name: default
  run_list:
  - "recipe[sc-mongodb]"

- name: replicaset
  run_list:
  - "recipe[sc-mongodb::replicaset]"
  attributes:
    mongodb:
      cluster_name: kitchen
      config:
        replSet: kitchen

- name: configserver
  run_list:
  - "recipe[sc-mongodb::configserver]"

- name: mongos
  run_list:
  - "recipe[sc-mongodb::mongos]"
  attributes:
    mongodb:
      cluster_name: default
      config:
        configdb: my_configserver

- name: mms_monitoring_agent
  run_list:
  - "recipe[sc-mongodb::mms_monitoring_agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
        monitoring:
          sslRequireValidServerCertificates: false
  excludes:
    # Upstart is not present
    - debian-7.2.0

- name: mms_backup_agent
  run_list:
  - "recipe[sc-mongodb::mms_backup_agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
        backup:
          sslRequireValidServerCertificates: false
  excludes:
    # Upstart is not present
    - debian-7.2.0

- name: user_management
  run_list:
  - "recipe[sc-mongodb::default]"
  - "recipe[sc-mongodb::user_management]"
  attributes:
    mongodb:
      install_method: mongodb-org
      # Needed to read the correct config file
      # since mongo 2.6
      default_init_name: mongod
      dbconfig_file: mongodb.conf
      config:
        auth: true
